# Generated by Django 5.2.4 on 2025-07-23 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilolo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_participants', models.IntegerField(default=8)),
                ('highlights', models.TextField()),
                ('what_included', models.TextField()),
                ('what_to_bring', models.TextField()),
                ('meeting_point', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'db_table': 'tour',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='user',
        ),
        migrations.CreateModel(
            name='TourSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='pilolo.tour')),
            ],
            options={
                'verbose_name': 'Tour Schedule',
                'verbose_name_plural': 'Tour Schedules',
                'db_table': 'tour_schedule',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.IntegerField(default=1)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('tour_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('special_requirements', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilolo.tourschedule')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'booking',
                'ordering': ['-booking_date'],
            },
        ),
    ]
