# Generated by Django 5.2.4 on 2025-07-29 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilolo', '0003_alter_booking_participants_alter_booking_schedule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bookingparticipant',
            options={},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='participants',
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='booking',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bookingparticipant',
            table=None,
        ),
    ]
