# Generated by Django 5.2.4 on 2025-07-30 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilolo', '0005_alter_booking_options_alter_booking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourschedule',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
