# Generated by Django 5.2.4 on 2025-07-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilolo', '0006_tourschedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
