# Generated by Django 5.2.4 on 2025-07-31 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilolo', '0007_booking_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingparticipant',
            options={'ordering': ['full_name'], 'verbose_name': 'Booking Participant', 'verbose_name_plural': 'Booking Participants'},
        ),
        migrations.AlterModelTable(
            name='bookingparticipant',
            table='booking_participant',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pilolo.booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payment',
            },
        ),
    ]
