# Generated by Django 5.2.4 on 2025-07-31 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilolo', '0008_alter_bookingparticipant_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
    ]
