# Generated by Django 5.2.4 on 2025-08-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilolo', '0009_remove_booking_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
